name: 'Install Apache Thrift Compiler'
description: 'Install Apache Thrift Compiler in Github Actions'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  version:
    description: 'Thrift version to install'
    required: true
    default: '0.15.0'
runs:
  using: composite
  steps:
    - name: Prepare
      shell: bash
      run: |
        mkdir -p ./.setup-thrift/oras
        mkdir -p ./.setup-thrift/thrift

    - name: Install ORAS
      shell: bash
      working-directory: ./.setup-thrift/oras
      run: |
        curl -sLO  https://github.com/deislabs/oras/releases/download/v0.7.0/oras_0.7.0_linux_amd64.tar.gz \
        && tar -xvzf oras_0.7.0_linux_amd64.tar.gz \
        && sudo ln -s $(pwd)/oras /usr/local/bin/oras

    - name: Install thrift
      shell: bash
      working-directory: ./.setup-thrift/thrift
      run: |
        oras pull ghcr.io/dodopizza/setup-thrift/binaries:v${{ inputs.version }} \
          --media-type application/vnd.unknown.layer.v1+tar.gz \
        && tar zxf ./thrift.v${{ inputs.version }}.tar.gz -C . \
        && sudo ln -s $(pwd)/thrift /usr/local/bin/thrift
