name: 'Apache Thrift Actions wrapper'
description: 'Run Apache Thrift in Github Actions'
inputs:
  command:
    description: "Command to run"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}