name: Main

on:
  - push

jobs:
  build-executable:
    name: Build executable
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version:
          # - v0.13.0
          # - v0.14.0
          # - v0.14.1
          # - v0.14.2
          - v0.15.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build thrift
        run: sh ./build.sh ${{ matrix.version }}

      - name: Install ORAS
        run: |
          curl -sLO  https://github.com/deislabs/oras/releases/download/v0.7.0/oras_0.7.0_linux_amd64.tar.gz && \
          tar -xvzf oras_0.7.0_linux_amd64.tar.gz && \
          sudo cp ./oras /usr/local/bin/

      - name: Login
        run: | 
          echo ${{ secrets.GITHUB_TOKEN }} | oras login https://ghcr.io -u aurokk --password-stdin

      - name: Upload
        run: |
          oras push ghcr.io/dodopizza/thrift-action/binaries:1.0 \
            ./dist/thrift.${{ matrix.version }}.tar.gz:application/vnd.unknown.layer.v1+tar.gz

      - name: Download
        run: |
          oras pull ghcr.io/dodopizza/thrift-action/binaries:1.0 \
            --media-type application/vnd.unknown.layer.v1+tar.gz \
          && tar zxf thrift.tar.gz -C ./x dist/thrift.v0.15.0.tar.gz \
          && ls -laR ./x